
os: linux
matrix:
    fast_finish: true
    include:
      - env: TEST_SUITE=ios
        language: objective-c
cache:
  directories:
    - npm
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $HOME/android-ndk-r18b
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
install:
  - |
    case $TEST_SUITE in
      "ios")
        # install nodejs dependences
        npm install
        # install python dependences
        cd e2etest && pip install -r requirements.txt && cd ..
        # install ios dependences
        cd ios && pod install --repo-update
        ;;
    esac
script:
  - |
    case $TEST_SUITE in
      "ios")
        hasIosFile=$(npm run danger -- run --dangerfile ./dangerfile-ios.js)
        echo "The value of hasIosFile is ${hasIosFile}"
        if [[ "$hasIosFile" =~ "hasIosFile" ]]; then
          # convert App.vue to e2e-landing.js
          cp common/App.vue vue-build/ && cd vue-build/
          npm install
          npm run build:weex
          # cp App.js to ios project
          cp e2e-landing.js ../ios/bundlejs/ && cd ../ios/
          # build project and output .app
          xcodebuild -quiet -workspace WeexDemo.xcworkspace -scheme WeexDemo CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform=iOS Simulator,name=iPhone 6" -derivedDataPath build
          # zip WeexDemo.app
          cd  build/Build/Products/Debug-iphonesimulator/
          zip -r WeexDemo.app.zip WeexDemo.app
          # upload file to sauceLab server
          curl -u "renmin:6b19f4d0-7119-4151-9acd-a5f39d242167" -X POST -H "Content-Type: application/octet-stream" https://saucelabs.com/rest/v1/storage/renmin/weexplayground-ios.zip\?overwrite\=true --data-binary @WeexDemo.app.zip
          # run e2e test
          cd ../../../../../e2eTest &&  python appium-ios-test.py
        fi
        ;;
    esac
notifications:
  webhooks:
    on_pull_requests: false
    urls:
      - https://oapi.dingtalk.com/robot/send?access_token=5a6be5eb6ad180fa4d04bdda0b24857ee49c3dd985361efdf0964aa9134ee623
    on_success: never 
    on_failure: always
  email:
    recipients:
      - weexnotify@gmail.com
    on_success: never
    on_failure: always

